### ISSUE TITLE
Add Common Room tracking

### ISSUE THREAD

**Issue by sarahmk125** [PrefectHQ/docs#786]
Add this script to the new docs site so we can do prospecting for large accounts viewing our docs
https://commonroomnyc.notion.site/Common-Room-Website-Tracking-Setup-Instructions-Prefect-b330838347144d1b879b3210f6db4a22

**Comment by discdiver** [comment]
Closing as completed. If changes needed, please open an issue in prefecthq/prefect with the `docs` label.
